### PR TITLE
(wip) Resurrects support for Java UUID from #123. Fixes #122

### LINKED ISSUE #122: UUID is missing
Could java.util.UUID be added to the bundled types please? It is frequently used type.

### PR DESCRIPTION
**Pull request by eed3si9n**
- Adjusted to a la carte style pickler.
#123. Fixes #122

### CODE REVIEW

**Comment by jsuereth** [comment]
LGTM

**Comment by eed3si9n** [comment]
I should've put (wip) on the title. @heathermiller has objected to this PR in https://github.com/scala/pickling/pull/123#issuecomment-73406955:

> In any case, I'd now advocate not shipping custom serializers for widely-used Java classes. Why? Version-hell could ensue if pickling supports the shape of some object for some specific Java version but not others. You'd wind up with all kinds of confusing serialization errors without realizing that pickling is special-casing that specific Java type for a different version than you're using.

**Comment by heathermiller** [comment]
I don't object this PR – I think it's OK for now. I just advocate fixing whatever Java sharp corner pickling is getting stuck on. This way potential versioning issues can be avoided. 

In the past though, such fixes were not quick/easy, sadly :/

**Comment by eed3si9n** [comment]
@heathermiller ok. My attempt at the sharp-corner handling is #295, which is still not complete, but I'd like your opinion on the matter.

**Pull request merged**
