### PR TITLE
Scala Pickling 0.10.1

### PR DESCRIPTION
**Pull request by eed3si9n**
This is the published commit for 0.10.1.

/review @jsuereth

### CODE REVIEW

**Comment by eed3si9n** [comment]
Note I had to switch sbt version to 0.13.9-SNAPSHOT due to sbt/sbt#1834

**Comment by phaller** [comment]
Great- thanks, Eugene!

Question: why remove sbt-pgp from `project/plugins.sbt`?

**Comment by eed3si9n** [comment]
@phaller I have a newer version of sbt-pgp from another organization name `com.jsuereth` as a global plugin, so the build failed to load. Generally I like putting things like sbt-pgp (and IDE related plugins if I used IDEs) to global plugin instead of the project itself.

**Comment by phaller** [comment]
OK, makes sense. Which version of sbt-pgp are you using? Just curious.

The `com.jsuereth` organization is pretty cool, though. Maybe we should all become members. :-)

**Comment by eed3si9n** [comment]
I've been saying we should just fold that feature into [sbt mothership since 2013](https://groups.google.com/forum/#!topic/simple-build-tool/1Zq1Xa5_Ge4).

Here's what I have on my global:

```
$ cat ~/.sbt/0.13/plugins/pgp.sbt 
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.0")
```

**Comment by phaller** [comment]
OK, thanks!

**Comment by phaller** [comment]
LGTM

**Comment by phaller** [comment]
Can you rebase, @eed3si9n? Thanks!

**Comment by eed3si9n** [comment]
I think I should manually merge, since one of the commits are tagged, I don't want to lose that.

**Comment by phaller** [comment]
Good point.

**Comment by eed3si9n** [comment]
Merged manually.

**Comment by phaller** [comment]
Thanks!

**Pull request merged**
