### PR TITLE
Fix #302 - source jar is not correctly packed

### LINKED ISSUE #302: source jar is not correctly packed
The sources need to be inside of their correct packages. To me it seems that the `scala` package got somehow stripped away:

```
% jar tf ~/.ivy2/cache/org.scala-lang.modules/scala-pickling_2.11/srcs/scala-pickling_2.11-0.10.0-sources.jar
META-INF/MANIFEST.MF
pickling/
pickling/binary/
pickling/internal/
pickling/ir/
pickling/json/
pickling/pickler/
pickling/refs/
pickling/runtime/
pickling/static/
pickling/util/
scala/
scala/pickling/
pickling/pickler/JavaBigInteger.scala
pickling/Compat.scala
pickling/pickler/Date.scala
scala/pickling/directSubclasses.java
pickling/Ops.scala
pickling/FileOutput.scala
pickling/pickler/Primitives.scala
pickling/pickler/Array.scala
pickling/Output.scala
pickling/pickler/List.scala
pickling/pickler/PrimitiveArrays.scala
pickling/refs/package.scala
pickling/pickler/AllPicklerUnpicklers.scala
pickling/PBuilderReader.scala
pickling/runtime/GlobalRegistry.scala
pickling/Pickler.scala
pickling/pickler/Any.scala
pickling/pickler/GenUnpicklers.scala
pickling/runtime/Runtime.scala
pickling/binary/BinaryInput.scala
pickling/pickler/Set.scala
pickling/runtime/RuntimePicklerLookup.scala
pickling/ir/IRs.scala
pickling/pickler/Ref.scala
pickling/pickler/ArrayBuffer.scala
pickling/functions.scala
pickling/static/package.scala
pickling/binary/Util.scala
pickling/pickler/Map.scala
pickling/pickler/Iterable.scala
pickling/util/Externalizables.scala
pickling/internal/Classes.scala
pickling/FastTags.scala
pickling/HasCompat.scala
pickling/Defaults.scala
pickling/PickleFormat.scala
pickling/binary/BinaryPickleFormat.scala
pickling/runtime/RuntimePickler.scala
pickling/internal/AppliedType.scala
pickling/pickler/Vector.scala
pickling/Tools.scala
pickling/runtime/RuntimeUnpicklerLookup.scala
pickling/runtime/CustomRuntime.scala
pickling/pickler/GenPicklers.scala
pickling/binary/BinaryPickle.scala
pickling/binary/BinaryOutput.scala
pickling/util/ArrayObjectOutput.scala
pickling/Macros.scala
pickling/json/JSONPickleFormat.scala
pickling/pickler/JavaBigDecimal.scala
pickling/binary/package.scala
pickling/internal/package.scala
pickling/pickler/Seq.scala
```

### PR DESCRIPTION
**Pull request by phaller**
Move the source tree of the 'core' project to the correct
directory.

### CODE REVIEW

**Comment by jsuereth** [comment]
I'm always nervous to merge these types of changes because they break every pending PR, but it does LGTM.

**Comment by heathermiller** [comment]
Seems sensible... But +1 on Josh's point about pending PRs.

**Comment by heathermiller** [comment]
I suppose that's OK though. There aren't many PRs in the queue, and they're all essentially from us. We can handle fixing them up for merge, if necessary. So, LGTM!

**Comment by jsuereth** [comment]
Ok! merged. Thanks @phaller for fixing this.

**Pull request merged**
